#!/bin/sh
# Create D4 ParFlow slope files
set -e

topo_nc="./HSURFBurnedAndMod.nc"

# Use PriorityFlow to calculate the slopes, akin to
# GRASS' r.watershed (sva_static_pfl.ncl)
Rscript create_pfl_slopes.R

